
volumes:
  spoties_data:

services:
  spoties:
    image: ghcr.io/vincent/spoties:latest
    hostname: spoties
    restart: unless-stopped
    volumes:
      - spoties_data:/srv/spoties/data
    ports:
      - 80:1080
      - 443:1443
