
volumes:
  spoties_data:

services:
  spoties:
    image: ghcr.io/vincent/spoties:main
    hostname: spoties
    restart: unless-stopped
    environment:
      - SPOTIES_FQDN=
      - SPOTIES_CLOUDFLARE_TOKEN=
    volumes:
      - spoties_data:/srv/spoties/data
    ports:
      - 80:80
      - 443:443
