
services:
  spoties:
    image: ghcr.io/vincent/spoties:main
    restart: unless-stopped
    volumes:
      - spoties_data:/srv/spoties/data
    ports:
      - 8090:8090

volumes:
  spoties_data: # for persistent database
