name: CI
on:
  push:
    branches:
      # change this if your primary branch is not main
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache-dependency-path: "frontend"
          cache: 'npm'

      - name: Copy secrets
        working-directory: ./frontend
        run: |
          echo PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.PUBLIC_GOOGLE_MAPS_API_KEY }} > .env

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Prepare
        run: |
          mkdir -p next/backend
          cp -Rf ./deployment            ./next/deployment
          cp -Rf ./frontend/build        ./next/frontend
          cp -Rf ./backend/data          ./next/backend/
          cp -Rf ./backend/pb_*          ./next/backend/
          cp -Rf ./backend/go.mod        ./next/backend/
          cp -Rf ./backend/go.sum        ./next/backend/
          cp -Rf ./backend/main.go       ./next/backend/
          cp -Rf ./backend/pocketbase    ./next/backend/
          cp -Rf ./backend/modd*         ./next/backend/

      - name: Copy artefacts
        uses: appleboy/scp-action@v0.1.7
        with:
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          strip_components: 1
          source: "next"
          rm: true
          target: /srv/spoties/next

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: CLOUDFLARE_DNS_TOKEN="${{ secrets.CLOUDFLARE_DNS_TOKEN }}" POCKETBASE_DATADIR="${{ secrets.POCKETBASE_DATADIR }}" POCKETBASE_ADMIN_EMAIL="${{ secrets.POCKETBASE_ADMIN_EMAIL }}" POCKETBASE_ADMIN_PASSWORD="${{ secrets.POCKETBASE_ADMIN_PASSWORD }}" bash /srv/spoties/next/deployment/install.sh
